### ISSUE TITLE
can't initiate database locally

### ISSUE THREAD

**Issue by FelipeEmos** [w3cj/hono-open-api-starter#21]
Can't run the app locally because of the following error on `pnpm drizzle-kit studio`

```
TypeError: Cannot read properties of undefined (reading 'tasks')
    at https://local.drizzle.studio/index.js:641:612
    at Array.map (<anonymous>)
    at pull (https://local.drizzle.studio/index.js:641:483)
    at async pull (https://local.drizzle.studio/index.js:641:5909)
    at async zKl (https://local.drizzle.studio/index.js:14267:56741)
```

![image](https://github.com/user-attachments/assets/552eeb12-0426-4415-9665-a616c4a6118d)

When opening the References OpenAPI page I get:
```
Oops, something went wrong here.
TypeError: Cannot read properties of undefined (reading 'uid')
```
![image](https://github.com/user-attachments/assets/2a2a1bc7-8ce4-4054-b3da-6bc087d1f829)

**Comment by FelipeEmos** [comment]
After a bunch of tweaking, trying to get to a stable, valid and simple database state, my investigation led to the `schema.ts`

Here's the fix......
```diff ts
export const tasks = sqliteTable("tasks", {
  id: integer("id", { mode: "number" })
    .primaryKey({ autoIncrement: true })
+   .unique(),
  name: text("name")
    .notNull(),
  // ... rest of the schema
});
```

I mean, it's crazy to think the `primaryKey` from drizzle wouldn't by default consider it a unique field, but that's my conclusion. I guess the lack of a `unique` field is messing up with the table creation.
